# Generated by Django 5.1.5 on 2025-07-12 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmedia',
            name='content_type',
            field=models.CharField(choices=[('video', 'video'), ('image', 'image')], max_length=50),
        ),
    ]
