# Generated by Django 5.1.5 on 2025-07-11 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='verfied',
            new_name='verified',
        ),
    ]
