# Generated by Django 5.2.5 on 2025-11-06 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_user_about_me_alter_user_bio_alter_user_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cover',
            field=models.ImageField(blank=True, default='bb-9.jpg', null=True, upload_to='Profilecover'),
        ),
        migrations.AlterField(
            model_name='user',
            name='img',
            field=models.ImageField(blank=True, default='1.png', null=True, upload_to='ProfileImg'),
        ),
    ]
