# Generated by Django 5.2.5 on 2025-08-21 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='caption',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
