# Generated by Django 5.2.5 on 2025-08-21 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0002_alter_story_caption'),
    ]

    operations = [
        migrations.RenameField(
            model_name='story',
            old_name='video',
            new_name='file',
        ),
        migrations.RemoveField(
            model_name='story',
            name='image',
        ),
    ]
