# Generated by Django 5.1.5 on 2025-07-12 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='messageattachment',
            name='url',
            field=models.URLField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
