# Generated by Django 5.1.5 on 2025-07-13 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0002_messageattachment_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messageattachment',
            name='url',
        ),
    ]
