# Generated by Django 5.1.5 on 2025-07-13 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0003_remove_messageattachment_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='messageattachment',
            name='file_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
