# Generated by Django 5.1.5 on 2025-08-11 13:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0010_conversation_admin'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversation',
            name='admin',
        ),
        migrations.AddField(
            model_name='conversation',
            name='admin',
            field=models.ManyToManyField(related_name='conversation_admin', to=settings.AUTH_USER_MODEL),
        ),
    ]
