# Generated by Django 5.2.5 on 2025-08-21 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0011_remove_conversation_admin_conversation_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='group_name',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
